spring.application.name=student_credentials

spring.datasource.username=postgres
spring.datasource.password=geheim123
spring.datasource.url=jdbc:postgresql://localhost:5432/pos4d_pizza_2526
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
