spring.application.name=student_credentials

spring.datasource.username=postgres
spring.datasource.password=geheim123
spring.datasource.url=jdbc:postgresql://studentDB:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop